# Generated by Django 6.0.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_paymenttransaction'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.UniqueConstraint(
                condition=models.Q(('provider_transaction_id', ''), _negated=True),
                fields=('provider', 'provider_transaction_id'),
                name='uniq_provider_transaction_id',
            ),
        ),
    ]
