# Generated by Django 6.0.7 on 2026-08-16 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_uniq_provider_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='amount',
            field=models.PositiveIntegerField(help_text='Amount in tiyin (UZS minor units), snapshotted at checkout. Intentional: reused created/pending rows keep this amount even if Book.price_tiyin or BOOK_PRICE_TIYIN changes later (not live-priced).'),
        ),
    ]
